select
udftest.ice_to_char(time,'SSSS') as col1,
udftest.ice_to_char(time,'SSSS.SS') as col2,
udftest.ice_to_char(time,'SSSS-YY') as col3,
udftest.ice_to_char(time,'HH:MM') as col4,
udftest.ice_to_char(time,'MI') as col5,
udftest.ice_to_char(time,'SS') as col6,
udftest.ice_to_char(time,'YYYY') as col7,
udftest.ice_to_char(time,'HH24') as col8,
udftest.ice_to_char(time,'J') as col9,
udftest.ice_to_char(time,'JJ') as col10,
udftest.ice_to_char(time,'SSJ') as col11,
udftest.ice_to_char(time,'MM') as col12,
udftest.ice_to_char(time,'DDDD') as col13,
udftest.ice_to_char(time,'YYMMDD') as col14,
udftest.ice_to_char(time,'YYDDMM') as col15,
udftest.ice_to_char(time,'HH12') as col16,
udftest.ice_to_char(time,'RM') as col17,
udftest.ice_to_char(time,'rm') as col18,
udftest.ice_to_char(time,'YYYY-MM-DD HH:MI:SS.SSSS AM') as col19,
udftest.ice_to_char(time,'YYYY-MM-DD HH:MI:SS.SSSS a.m') as col20,
udftest.ice_to_char(time,'YYYY-month-DD') as col21,
udftest.ice_to_char(time,'YYYY-MON-DD') as col22,
udftest.ice_to_char(time,'SSSS-YY') as col23,
udftest.ice_to_char(time,'YYYY-MM,DAY') as col24,
udftest.ice_to_char(time,'YYYY-MONTH-DY') as col25,
udftest.ice_to_char(time,'YYYY-MONTH-dy') as col26,
udftest.ice_to_char(time,'DDD') as col27,
udftest.ice_to_char(time,'HH24') as col28,
udftest.ice_to_char(time,'CC') as col29,
udftest.ice_to_char(time,'Q') as col30
from udftest.pos_tbl
limit 5;

